# --- !Ups
CREATE TABLE TASK(
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(510) NOT NULL,
  COMPLETED_DATE DATETIME DEFAULT NULL,
  DAILY_FLAG tinyint(1) DEFAULT 0,
  PRIMARY KEY (id)
);

# --- !Downs
DROP TABLE TASK;