# --- !Ups
ALTER TABLE TASK ADD STEPS_DONE TINYINT NOT NULL DEFAULT '0';
ALTER TABLE TASK ADD NO_STEPS TINYINT NOT NULL DEFAULT '1';
ALTER TABLE TASK ADD NO_DAYS_REPEAT TINYINT NOT NULL DEFAULT '0';
CREATE TABLE ACCOUNT(
  USERNAME VARCHAR(50) NOT NULL,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(120) NOT NULL,
  PRIMARY KEY(USERNAME)
);
CREATE TABLE ACCOUNT_PRIVATE(
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIMARY KEY(USERNAME),
  FOREIGN KEY(USERNAME) REFERENCES ACCOUNT(USERNAME)
);

# --- !Downs
ALTER TABLE TASK DROP STEPS_DONE;
ALTER TABLE TASK DROP NO_STEPS;
ALTER TABLE TASK DROP NO_DAYS_REPEAT;
DROP TABLE ACCOUNT;
DROP TABLE ACCOUNT_PRIVATE;