# --- !Ups
ALTER TABLE TASK ADD STEPS_DONE TINYINT NOT NULL DEFAULT '0';
ALTER TABLE TASK ADD NO_STEPS TINYINT NOT NULL DEFAULT '1';
ALTER TABLE TASK ADD NO_DAYS_REPEAT TINYINT NOT NULL DEFAULT '0'

# --- !Downs
ALTER TABLE TASK DROP STEPS_DONE;
ALTER TABLE TASK DROP NO_STEPS;
ALTER TABLE TASK DROP NO_DAYS_REPEAT;